# Generated by Django 3.2 on 2022-12-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование курса')),
                ('date_started', models.DateField(verbose_name='Дата начала курса')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название курса')),
                ('month_to_learn', models.IntegerField(verbose_name='Продолжительность курсов')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('work_study_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место работы/учебы')),
                ('has_own_notebook', models.BooleanField(default=False, verbose_name='Имеет ли свой ноутбук')),
                ('preferred_os', models.CharField(choices=[('mac', 'MacOS'), ('windows', 'Windows'), ('linux', 'Linux')], max_length=30, verbose_name='Предпочитаемая ОС')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('main_work', models.CharField(blank=True, max_length=40, null=True, verbose_name='Основное место работы')),
                ('experience', models.DateField(verbose_name='Опыт работы')),
                ('students', models.ManyToManyField(related_name='studs', through='user.Course', to='user.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='user.mentor'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
